### ISSUE TITLE
Remove heading from webpage

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/auto-dl.github.io#1]
Remove the <header> tag from web page

![image](https://user-images.githubusercontent.com/39651310/92942928-bc8b1480-f46f-11ea-8ca7-56178e023c33.png)

Please remove that crossed part.

**Comment by shubhamgoel24** [comment]
Hello
I would like to help

**Comment by ADI10HERO** [comment]
Hello @shubhamgoel24 , thank you for reaching out.

This issue was fixed but since the code is not yet merged in master, the issue is still open.

PS: 
Are you a SLoP mentee?
Also, can you please join our Gitter room for discussion (check readme)

**Comment by shubhamgoel24** [comment]
Ohk
No problem
