### ISSUE TITLE
Image and Logo should be responsive

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/auto-dl.github.io#23]
Please make the image and logo to be responsive....
We've speculated that those 2 images are stopping the whole page from being responsive...

Thanks

**Comment by saurabhhere** [comment]
I think only Image is stopping from being responsive, can you please tell about which logo are you talking.
Thanks

**Comment by ADI10HERO** [comment]
@saurabhhere 
The main AutoDL logo that can also be seen on the Orgs' [profile](https://github.com/Auto-DL) 
If you bring down the page's width to I don't know, smaller screen mobile phones? You'll see even the logo stops the page from being responsive
