### ISSUE TITLE
Change select color to blue

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/auto-dl.github.io#31]
Before:
![image](https://user-images.githubusercontent.com/39651310/98640709-82939d00-2350-11eb-989f-298dd30ab20c.png)

After:
![image](https://user-images.githubusercontent.com/39651310/98640793-ad7df100-2350-11eb-9e0a-30d525d7126f.png)

Basically switch the hover and default select color 

Thanks

**Comment by Vrindagupta6828** [comment]
@ADI10HERO Please assign me this issue.
