### ISSUE TITLE
Would like to do some UI updated to auto-dl.tech landing page

### ISSUE THREAD

**Issue by adithyapaib** [Auto-DL/auto-dl.github.io#51]
## Feature Request

Is your feature request related to an existing [Issue](https://www.github.com/Auto-DL/Generator/issues) or a new implementation?

### Feature Description

Add coloured scrollbar 
Add meta theme tag

### Possible Solution

If assigned I will PR it

**Comment by ADI10HERO** [comment]
Hey @adithyapaib could you have a look at [this](https://vedant080102.github.io/auto-dl.github.io/) and see if you're interested in updating something. Code for that deployment is available in the "v2" branch of this repo.

**Comment by niyoj** [comment]
Is this issue open to contribute?

**Comment by ADI10HERO** [comment]
Hey @niyoj  Yes it is :)

**Comment by niyoj** [comment]
Can you assign this to me?

**Comment by niyoj** [comment]
@ADI10HERO I am successful to do the following changes;
- Add colored scrollbar
- Add meta-theme tag

Are there any things remaining to update?

The final look like this 
![Screenshot from 2021-10-07 19-06-49](https://user-images.githubusercontent.com/84063586/136392750-2a3bad8e-4e62-4fab-a139-69d3cf2c4546.png)

**Comment by ADI10HERO** [comment]
I think this looks for now. @rajraj889, mind having a look too?

@niyoj Did you find some issues/bugs while running the site? Like "oh, this could have been done better!"

**Comment by ADI10HERO** [comment]
Also, @niyoj, did you forget to "git add" changes for the meta-theme tag?

**Comment by niyoj** [comment]
@ADI10HERO I did add that but the theme meta-tags effect is not seen on laptop browsers. But here is the screenshot when I view the website from my mobile browser.
![Screenshot_20211007-205554](https://user-images.githubusercontent.com/84063586/136413281-e40ec751-53e1-40a1-864e-4dcc170508f0.png)

**Comment by niyoj** [comment]
Can I PR now if everything is all done? I will be adding some more PRs if I find something that needs to be changed or will open an issue.

**Comment by ADI10HERO** [comment]
Yep, merged the PR. Will create more issue if needed :)

**Comment by niyoj** [comment]
@ADI10HERO I have not sent a PR yet??
