### ISSUE TITLE
Add "Join our Slack Community" badge to readme 

### ISSUE THREAD

**Issue by ADI10HERO** [Auto-DL/auto-dl.github.io#6]
Please find how it is done ideally in popular open source orgs, "badge" is not a compulsion, just somehow (correct way) link to the slack channel should be there.

**Comment by georgettica** [comment]
can I take this?

**Comment by georgettica** [comment]
I found https://github.com/breakzplatform/slack-list-brazil

**Comment by georgettica** [comment]
also found a format that works:
[![Get on Slack](https://img.shields.io/badge/slack-join-orange.svg)](https://join.slack.com/t/apache-superset/shared_invite/enQtNDMxMDY5NjM4MDU0LWJmOTcxYjlhZTRhYmEyYTMzOWYxOWEwMjcwZDZiNWRiNDY2NDUwNzcwMDFhNzE1ZmMxZTZlZWY0ZTQ2MzMyNTU)

can be pasted on markdown

**Comment by georgettica** [comment]
lastly I need the link to put,
can you follow the steps in https://slack.com/intl/en-il/help/articles/201330256-Invite-new-members-to-your-workspace#share-an-invite-link

and paste the url given from this so I can create a PR with the correct badge?

**Comment by ADI10HERO** [comment]
@georgettica 
Thank you so much for showing interest.
Here you go :) 
 
 https://join.slack.com/t/autodl/shared_invite/zt-ig3dwj68-4U_lfyQeb5LZueKZbNyDXw

**Comment by georgettica** [comment]
@shintan777 if I showed interest please don't take the work from me.
I was going to do the PR when I got all the resources
